# Homework on Statistical Learning Theory

<b>Deadline:</b> 24.12.2018, 9 a.m. (there would be no soft deadline)

<b>How to hang in?</b> You need to put your Jupyter Notebook to GitHub repo and send link in Telegram to <b>@CroCode</b>

Felipe Vaca

### Block №1. Combinatorics and Probability Theory

You can use LaTeX expressions in order to provide formulas: https://en.wikibooks.org/wiki/LaTeX

1) In how many ways can the letters of the word PROBABILITY be rearranged such that all I’s and P’s appear in the middle?

<b>Total:</b> 1 point

The word PROBABILITY has 11 letters. Since all I's and P's appear in the middle, the 8 remaining letters can be arranged in $\frac{8!}{2!} = 20160$; the denominator is included because there are two B's. 

The I's and P's can be also rearranged in the middle positions in $\frac{3!}{2!} = 3$, ; the denominator is included because there are two I's. 

Thus, the number of ways in which the letters of the word PROBABILITY can be rearranged such that all I’s and P’s appear in the middle is $20160 (3) = 60480$.

2) The probability of having defect (at least 1 defective product) in batch of 100 products is 63.2%. Find the probability of having less than 3 defective products in such a batch.

<i>Hint:</i> use idea of Poisson distribution (https://en.wikipedia.org/wiki/Poisson_distribution)

<b>Total:</b> 1.5 points

Let $\textbf{X}$ be the random variable "number of defective products out of 100". A first approach consists on modelling $\textbf{X}$ as a binomial random variable, i.e. $\textbf{X} \sim Bin(100,0.632)$. In this case, $P(X<3) = \sum_{i=0}^2 C_{i}^{100} (0.632)^{i} (1-0.632)^{100-i} \approx 5.68 * 10^{-40}$

The binomial distribution can be approximated by a Poisson distribution when n is "large" and p is "small", by setting $\lambda = np$. In this case, I do not consider that p fulfills such requirement. Nevertheless, I report the results:

$P(X<3) = \sum_{i=0}^2 \frac{e^{-100(0.632)}(100(0.632))^i}{i!} \approx 7.36 * 10^{-25}$.

### Block №2. Data Structures and Algorithms

<b><i>NB!</i></b> Here you need to provide solution having minimal memory and runtime complexity in terms of Big O notation.

3) Suggest an algorithm that resets all elements in the column <i>i</i> and the row <i>j</i> of the matrix M to zeros if the element in the <i>(i, j)</i> cell is zero. Provide solution having minimal memory and runtime complexity in terms of Big O notation.

<b>Input:</b> matrix M

<b>Output:</b> modified according to condition matrix M

<b>Total:</b> 2 points

In [79]:
import numpy as np

#Input. M :a matrix of dimension m x n
def g(M):
    nr = np.shape(M)[0]
    nc = np.shape(M)[1]
    # 1. Create two row vectors filled with ones, r and c, of dimensions m x 1 and n x 1, respectively. 
    r = [1] * nr
    c = [1] * nc
    # 2. For each element M[i,j], if it is zero, then set r[i] and c[j] equal to 0. (The complexity of this step is O(mn))
    for i in np.arange(nr):
        for j in np.arange(nc):
            if M[i,j] == 0:
                r[i] = 0
                c[j] = 0
            else:
                pass
    # 3. The resulting matrix is given by M1 = r' * c.  (The complexity of this step is O(mn))    
    M1 = np.matmul(np.matrix(r).T, np.matrix(c))
    M1 = np.multiply(M1,M)
    # Return M1.    
    return (M1)
    # I noticed that an entry of the new matrix is non-null only when there are non-null entries on its corresponding row and column. 
    # Then the step 3 is is equivalent to perform the logical operation AND between all the possible pairs r[i] and c[j], for 
    # i = 1,...,m; j = 1,...,n

    
    

In [80]:
# Examples
M = np.matrix([[1,0,2],[0,1,1],[4,1,2]])
M1 = g(M)
print("M = \n",M)
print("M1 = \n",M1)

N = np.matrix([[1,1,2]])
print(g(N))

M = 
 [[1 0 2]
 [0 1 1]
 [4 1 2]]
M1 = 
 [[0 0 0]
 [0 0 0]
 [0 0 2]]


4) Imagine you have a square picture, each pixel of which can be black or white (you can interpret it as binary matrix). Develop an algorithm for finding the maximum sub-square consisting of only black pixels.

<b>Input:</b> binary matrix M (contains only 0-1 elements)

<b>Output:</b> <i>((a1, b1),(a2, b2))</i> where <i>(a1, b1)</i> and <i>(a2, b2)</i> stay for coordinates of upper-left and lower-right sub-square corners respectively

<b>Total:</b> 2.5 points

In [117]:
#import numpy as np
# Input. M: a square matrix of dimension n x n 
def maxsq(M):
    # a1, b1, a2, and b2 as above.   
    a1 = None
    a2 = None
    b1 = None
    b2 = None
    s = 0 # size of the maximun sub-square consisting of only black pixels.
    n = len(M)
    for i in np.arange(n):
        for j in np.arange(n):
            # The complexity of both loops is O(mn)
            # First, check potential candidates (i.e., whose value is 0) in the position M[i,j]
            if M[i,j] == 0:
                # If so, update coordinates and size of the sub-square consisting of only black pixels.
                # 
                a10 = i
                a20 = i
                b10 = j
                b20 = j
                s0 = 1              

                # Starting from this coordinate, try to find the maximum sub-square consisting of only black pixels.
                # First, explore the 'new' diagonal (going down and right from (a10,b10))
                k = 1
                while ((i+k) < n and (j+k) < n) and M[i+k,j+k] == 0:
                    # Second, check that all the elements of the rows of the subsquare equal zero
                    if np.sum(M[i:(i+k+1),j:(j+k+1)]) == 0:
                        a20 = i+k
                        b20 = j+k
                        s0 += 1
                        k += 1    
                    else:
                        break


                #   3.4 Repeat 3.3. until a sub-square of zeros is found. Update s with s = a2 - a1 + 1.
                # (The complexity of this step is O(mn))

                if s0 > s:
                    a1 = a10
                    b1 = b10
                    a2 = a20
                    b2 = b20
                    s = s0

                else:
                    pass

            else: 
                pass

    return ((a1,b1),(a2,b2),s) 

# Memory complexity: O(1), since we have only required a1, a2, b1, b2, and s. 
# Runtime complexity: O((mn)^2)

In [120]:
# Examples

M1 = np.matrix([[1,0,1],[0,1,1],[0,1,1]])
print(M1)
print(maxsq(M1))

M2 = np.matrix([[0,0,0],[0,0,0],[0,0,0]])
print(M2)
print(maxsq(M2))

M3 = np.matrix([[1,1,1],[1,1,1],[1,1,1]])
print(M3)
print(maxsq(M3))

M4 = np.matrix([[1,0,1],[0,0,1],[0,0,1]])
print(M4)
print(maxsq(M4))

[[1 0 1]
 [0 1 1]
 [0 1 1]]
((0, 1), (0, 1), 1)
[[0 0 0]
 [0 0 0]
 [0 0 0]]
((0, 0), (2, 2), 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]]
((None, None), (None, None), 0)
[[1 0 1]
 [0 0 1]
 [0 0 1]]
((1, 0), (2, 1), 2)


5) Imagine series of integer numbers having only 3, 5 or 7 of some power in their factorization (i.e. 1, 3, 5, 7, 9, 15 etc.). Given k you're asked to return k-th number in this series.

<i>Helpful link</i>: https://en.wikipedia.org/wiki/Fundamental_theorem_of_arithmetic

<b>Input:</b> integer number k

<b>Output:</b> k-th number of series

<b>Total:</b> 3 points

In [93]:
# Brute force algorithm: verify all the necessary numbers, starting from 1, until we reach k numbers of the series
# Input: k, the index of the k-th element of the series.

def f(k):
    x = None # x will contain the kth element of the series
    y = 1 # counter of the number of elements from the series (3^x)(5^y)(7^z), for non negative integers x, y, z,
    # that we have generated.
    
    if k == 1:
        x = 1
    else:
        n = 2
    
    while y < k:
        if (n % 3) == 0 or (n % 5) == 0 or (n % 7) == 0:
            x = n
            y += 1 

        n = n + 1
    return (x)

# Memory complexity: O(1)
# Runtime complexity: ...

In [107]:
# Examples
print([f(k) for k in np.arange(1,10)])
print(f(10000))

[1, 3, 5, 6, 7, 9, 10, 12, 14]
18420
